### ISSUE TITLE
ImportError: cannot import name DebugToolbarExtension

### ISSUE THREAD

**Issue by ohadpartuck** [mgood/flask-debugtoolbar#92] opened 2016-02-24 09:40 UTC
```
pip install flask-debugtoolbar
Requirement already satisfied (use --upgrade to upgrade): flask-debugtoolbar in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): Flask>=0.8 in /usr/local/lib/python2.7/dist-packages (from flask-debugtoolbar)
Requirement already satisfied (use --upgrade to upgrade): Blinker in /usr/local/lib/python2.7/dist-packages (from flask-debugtoolbar)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous in /usr/local/lib/python2.7/dist-packages (from flask-debugtoolbar)
Requirement already satisfied (use --upgrade to upgrade): werkzeug in /usr/local/lib/python2.7/dist-packages (from flask-debugtoolbar)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.8->flask-debugtoolbar)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/local/lib/python2.7/dist-packages (from Jinja2>=2.4->Flask>=0.8->flask-debugtoolbar)
$ python
>>> from flask_debugtoolbar import DebugToolbarExtension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name DebugToolbarExtension
```

1. works on localhost (mac) but not on production server
2. tried `pip uninstall` and reinstalling again

@mgood please help

**Comment by jeffwidman** [comment] 2016-06-29 23:57
I can't reproduce this, closing as it's most likely something wrong with your prod server. If you're still having issues, please report the distro, python version, etc

**Closed by jeffwidman** 2016-06-29 23:57 UTC
